public class ExceptionLecture {
    public static void main(String[] args) {

////        System.out.println(numbers[999]);
//
////        throw new Exception("Something bad happened");
////        System.out.println("hello world");
//        int[] numbers = {1, 2, 3};
//        int = x;
//        try{
//            x = numbers[100];
//            System.out.println(numbers[999]);
//        } catch (Exception e){
//            System.out.println("exception was thrown, this is me catching and handling");
//        }
//        System.out.println("Hello World");
//    }


    }
}






//try tries running code but also looks for errors and if there are any errors it is going to send the error to
// exception and it will let the code run but the error goes to the catch block